### ISSUE TITLE
Rare energy tracking bug in mafia can cause chronolith to fail its guard

### ISSUE THREAD

**Issue by ianknowles** [Kasekopf/looprobot#19]
Requires manually fetching the char status to update the correct energy value could be handled in task recovery

**Comment by Kasekopf** [comment]
Do you have an example log from when the tracking failed?

**Comment by ianknowles** [comment]
I can dig one out but theres not much to see. The task is correctly activating because mafia indicates we have enough energy to use chronolith, chronolith is used and fails. Fetching the charpane shows that mafia was overcounting by 1. Unless you are looking to try to spot root causes or if we get any messages to look out for.

**Comment by Kasekopf** [comment]
It still would be nice to track down this misalignment in the future, but for now the script should at least not crash. I'll close this issue, but please reopen if it crashes again in the new version.
