### ISSUE TITLE
Package.json doesn't build

### ISSUE THREAD

**Issue by Alium58** [Kasekopf/looprobot#21]
Believe cause of issue is I'm running Windows.

I'm getting
![image](https://github.com/user-attachments/assets/84de1a8c-03ab-4a35-900a-27890a975cb6)

Chaning this line in package.json
```
"build": "node --no-warnings --loader ts-node/esm/transpile-only ./build.mjs && cp src/ash/* dist/KoLmafia/scripts/looprobot",
```
to
```
"build": "node --no-warnings --loader ts-node/esm/transpile-only ./build.mjs && copy src\\ash\\* dist\\KoLmafia\\scripts\\looprobot",
```

allows me to build. I'd PR it but I'm not familiar enough to know if this update breaks it for unix users. So making an issue instead. As a workaround, I'm making this change when I want to build and undoing it when I want to commit to my PR

**Comment by Kasekopf** [comment]
Looks like that change *does* break my WSL setup. It looks like [garbo](https://github.com/loathers/garbage-collector/blob/main/packages/garbo/package.json#L9) uses `copyfiles` which may solve this exact problem!

**Comment by Kasekopf** [comment]
I added a new dev dependency on `copyfiles` which seems to still work on my WSL setup. Could you see if this works better for you now?

**Comment by Alium58** [comment]
Not working, I'll try building garbo. haven't attempted to in a while
![image](https://github.com/user-attachments/assets/0850b2f3-6527-4644-ac17-b8033e6005e9)

**Comment by Alium58** [comment]
only 87 PRs outdated haha. So did a yarn install followed by the build and seems to have worked
![image](https://github.com/user-attachments/assets/156629ea-e998-4955-aa1c-aa189ff728e6)

**Comment by Kasekopf** [comment]
You may also need to `yarn install` first here as well, to install `copyfiles`.

**Comment by Alium58** [comment]
genius works now! Didn't expect that but makes sense, need to actually get `copyfiles`

**Comment by Kasekopf** [comment]
Great!
