### ISSUE TITLE
Shadow bricks are still used in macros when daily uses are exhausted

### ISSUE THREAD

**Issue by ianknowles** [Kasekopf/looprobot#32]
In practice this is uncommon usually only seen on Day 2, but might cause aborts on Day 1 if more than 13 bricks are collected, bricks uses are correctly tracked at 13 so the task must not be checking them.

`_shadowBricksUsed                                                13`

```
Executing Orc Chasm/Oil Kill [Route]
Round 1: discordance executes a macro!
Round 1: discordance uses the shadow brick!
KoLmafia thinks it is round 2 but KoL thinks it is round 1
You're on your own, partner. ((Macro aborted.))```

**Comment by Kasekopf** [comment]
This should be fixed; please reopen if it still occurs.
